Repository ClibMouse/ClickHouse, pull requests merged in 2023-02, with the labels that each got.

#199 bug_fix_1332
  src/Client/ClientBase.cpp
  src/Functions/FunctionBinaryArithmetic.h
  src/Functions/Kusto/KqlArrayIif.cpp
  src/Functions/Kusto/KqlArraySort.cpp
  src/Functions/Kusto/KqlIndexOf.cpp
  src/Functions/Kusto/KqlRange.cpp
  src/Functions/Kusto/kqlDateTime.cpp
  src/Functions/Kusto/kqlToString.cpp
  src/Functions/dateTime64Diff.cpp
  src/Functions/toStartOfInterval.cpp
  src/Interpreters/executeQuery.cpp
  src/Parsers/ExpressionElementParsers.cpp
  src/Parsers/ExpressionListParsers.cpp
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
  src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLCastingFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLDataTypeFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.h
  src/Parsers/Kusto/KustoFunctions/KQLDynamicFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.h
  src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
  src/Parsers/Kusto/ParserKQLExtend.h
  src/Parsers/Kusto/ParserKQLJoin.cpp
  src/Parsers/Kusto/ParserKQLMVExpand.cpp
  src/Parsers/Kusto/ParserKQLMVExpand.h
  src/Parsers/Kusto/ParserKQLMakeSeries.cpp
  src/Parsers/Kusto/ParserKQLMakeSeries.h
  src/Parsers/Kusto/ParserKQLOperators.cpp
  src/Parsers/Kusto/ParserKQLOperators.h
  src/Parsers/Kusto/ParserKQLQuery.cpp
  src/Parsers/Kusto/ParserKQLQuery.h
  src/Parsers/Kusto/ParserKQLRange.cpp
  src/Parsers/Kusto/ParserKQLSummarize.cpp
  src/Parsers/Kusto/ParserKQLTimespan.cpp
  src/Parsers/Kusto/ParserKQLTopNested.cpp
  src/Parsers/Kusto/ParserKQLTopNested.h
  src/Parsers/Kusto/Utilities.h
  src/Parsers/tests/KQL/gtest_KQL_TopNested.cpp
  src/Parsers/tests/gtest_Parser.cpp
  tests/queries/0_stateless/02366_kql_func_string.reference
  tests/queries/0_stateless/02366_kql_func_string.sql
  utils/check-style/codespell-ignore-words.list
Labels: pr-bugfix

#212 Kusto-phase3: fix yaml style
  .github/workflows/clibmouse_pr.yml
Labels: pr-build

#213 Handle multi-word needles with has operators
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/ParserKQLOperators.cpp
  tests/queries/0_stateless/02366_kql_operator_in_sql.reference
  tests/queries/0_stateless/02366_kql_operator_in_sql.sql
Labels: pr-bugfix

#220 KQL_arithmetic
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
  src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.h
  src/Parsers/Kusto/KustoFunctions/KQLDynamicFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.cpp
  src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.h
  src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
  src/Parsers/tests/KQL/gtest_KQL_Math.cpp
  tests/queries/0_stateless/02366_kql_func_math.reference
  tests/queries/0_stateless/02366_kql_func_math.sql
Labels: pr-feature

#221 Kql isempty arg fix
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
  src/Parsers/tests/KQL/gtest_KQL_StringFunctions.cpp
  tests/queries/0_stateless/02366_kql_func_string.reference
  tests/queries/0_stateless/02366_kql_func_string.sql
Labels: pr-bugfix

#179 Summarize exception bug 2113 fix
  src/Parsers/Kusto/ParserKQLSummarize.cpp
  src/Parsers/tests/KQL/gtest_KQL_AggregateFunctions.cpp
  tests/queries/0_stateless/02366_kql_summarize.reference
  tests/queries/0_stateless/02366_kql_summarize.sql
Labels: pr-bugfix

#208 bug_fix_1413
  src/Parsers/Kusto/KustoFunctions/KQLCastingFunctions.cpp
  src/Parsers/tests/KQL/gtest_KQL_Conversion.cpp
  tests/queries/0_stateless/02366_kql_datatype.reference
  tests/queries/0_stateless/02366_kql_datatype.sql
Labels: pr-bugfix

#222 bug_fix_1490
  src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
  src/Parsers/tests/KQL/gtest_KQL_StringFunctions.cpp
  tests/queries/0_stateless/02366_kql_func_string.reference
  tests/queries/0_stateless/02366_kql_func_string.sql
Labels: pr-not-for-changelog

#216 bug_fix_2159
  src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
  src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.h
  src/Parsers/Kusto/ParserKQLOperators.cpp
  tests/queries/0_stateless/02366_kql_datatype.reference
  tests/queries/0_stateless/02366_kql_datatype.sql
  tests/queries/0_stateless/02366_kql_func_string.reference
  tests/queries/0_stateless/02366_kql_func_string.sql
Labels: pr-bugfix

#226 Attempt to supress a pylint finding
  tests/ci/get_robot_token.py
Labels: pr-not-for-changelog

#228 variance related functions --- 2252
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.h
  src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.cpp
  src/Parsers/Kusto/ParserKQLSummarize.cpp
  src/Parsers/tests/KQL/gtest_KQL_AggregateFunctions.cpp
  tests/queries/0_stateless/02366_kql_summarize.reference
  tests/queries/0_stateless/02366_kql_summarize.sql
Labels: pr-feature

#231 Kusto-phase3 : fixed some sub-query issues.
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.cpp
  src/Parsers/Kusto/ParserKQLOperators.cpp
  src/Parsers/Kusto/ParserKQLQuery.cpp
  src/Parsers/TokenIterator.cpp
  src/Parsers/tests/KQL/gtest_KQL_Count.cpp
  src/Parsers/tests/KQL/gtest_KQL_test_subquery.cpp
  tests/queries/0_stateless/02366_kql_count.reference
  tests/queries/0_stateless/02366_kql_count.sql
  tests/queries/0_stateless/02366_kql_test_subquery.reference
  tests/queries/0_stateless/02366_kql_test_subquery.sql
Labels: pr-bugfix

#229 Kusto p3 project away
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/ParserKQLProjectAway.cpp
  src/Parsers/Kusto/ParserKQLProjectAway.h
  src/Parsers/Kusto/ParserKQLQuery.cpp
  src/Parsers/Kusto/Utilities.cpp
  src/Parsers/Kusto/Utilities.h
  src/Parsers/tests/KQL/gtest_KQL_ProjectAway.cpp
  tests/queries/0_stateless/02366_kql_projectaway.reference
  tests/queries/0_stateless/02366_kql_projectaway.sql
Labels: pr-feature

#227 Fix linker error for good
  programs/keeper/CMakeLists.txt
  programs/keeper/Keeper.cpp
Labels: pr-not-for-changelog
