Repository ClibMouse/ClickHouse, pull requests merged in 2023-03, with the labels that each got.

#214 implementation of has_ipv4, has_any_ipv4, has_ipv4_prefix, and has_an…
  src/Functions/Kusto/kqlHasAnyIp.h
  src/Functions/Kusto/kqlHasAnyIpv4.cpp
  src/Functions/Kusto/kqlHasAnyIpv4Prefix.cpp
  src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.cpp
  src/Parsers/Kusto/KustoFunctions/KQLIPFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLIPFunctions.h
  src/Parsers/tests/KQL/gtest_KQL_IP.cpp
  tests/queries/0_stateless/02366_kql_func_has_any_ipv4.reference
  tests/queries/0_stateless/02366_kql_func_has_any_ipv4.sql
Labels: pr-feature

#239 add release notes
  src/Parsers/Kusto/KQL_ReleaseNote.md
Labels: pr-documentation

#243 Implement KQL getschema
  src/Interpreters/QueryNormalizer.cpp
  src/Parsers/ExpressionListParsers.cpp
  src/Parsers/Kusto/KQLDataType.cpp
  src/Parsers/Kusto/KQLDataType.h
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/KustoFunctions/KQLCastingFunctions.cpp
  src/Parsers/Kusto/ParserKQLGetSchema.cpp
  src/Parsers/Kusto/ParserKQLGetSchema.h
  src/Parsers/Kusto/ParserKQLQuery.cpp
  src/Parsers/Kusto/ParserKQLQuery.h
  src/Parsers/Kusto/ParserKQLStatement.cpp
  src/Parsers/Kusto/ParserKQLTable.cpp
  src/Parsers/Kusto/Utilities.cpp
  src/Parsers/Kusto/Utilities.h
  src/Parsers/tests/KQL/gtest_KQL_Conversion.cpp
  src/Parsers/tests/KQL/gtest_KQL_GetSchema.cpp
  src/Storages/IStorage.h
  src/Storages/System/IStorageSystemOneBlock.h
  src/Storages/System/StorageSystemSchema.cpp
  src/Storages/System/StorageSystemSchema.h
  src/TableFunctions/TableFunctionGetSchema.cpp
  src/TableFunctions/TableFunctionGetSchema.h
  src/TableFunctions/registerTableFunctions.cpp
  tests/queries/0_stateless/02366_kql_getschema.reference
  tests/queries/0_stateless/02366_kql_getschema.sql
Labels: pr-feature

#244 string functions 2249
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.cpp
  src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.h
  src/Parsers/tests/KQL/gtest_KQL_StringFunctions.cpp
  tests/queries/0_stateless/02366_kql_func_string.reference
  tests/queries/0_stateless/02366_kql_func_string.sql
Labels: pr-feature

#246 Bug fix 2167
  src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
  src/Parsers/tests/KQL/gtest_KQL_StringFunctions.cpp
  tests/queries/0_stateless/02366_kql_func_string.reference
  tests/queries/0_stateless/02366_kql_func_string.sql
Labels: pr-bugfix

#181 Bug fix 1333 resubmit
  src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
  src/Parsers/tests/KQL/gtest_KQL_StringFunctions.cpp
  tests/queries/0_stateless/02366_kql_func_string.reference
  tests/queries/0_stateless/02366_kql_func_string.sql
Labels: pr-bugfix

#251 Kusto-phase3: fixed the bug core dump if query end with pipe
  src/Parsers/Kusto/ParserKQLQuery.cpp
  src/Parsers/tests/KQL/gtest_KQL_General.cpp
Labels: pr-bugfix

#252 Kusto-phase3: fixed kql range issues
  src/Functions/Kusto/KqlRange.cpp
  tests/queries/0_stateless/02366_kql_range.reference
  tests/queries/0_stateless/02366_kql_range.sql
Labels: pr-bugfix

#254 bug fix 2425
  src/Parsers/Kusto/KustoFunctions/KQLGeneralFunctions.cpp
  tests/queries/0_stateless/02366_kql_func_general.reference
  tests/queries/0_stateless/02366_kql_func_general.sql
Labels: pr-bugfix

#256 Kusto-phase3 : fix sort issues
  src/Parsers/Kusto/ParserKQLSort.cpp
  src/Parsers/tests/KQL/gtest_KQL_Distinct.cpp
  src/Parsers/tests/KQL/gtest_KQL_Sort.cpp
  src/Parsers/tests/KQL/gtest_KQL_StringFunctions.cpp
  src/Parsers/tests/KQL/gtest_KQL_TopHitter.cpp
  src/Parsers/tests/gtest_Parser.cpp
  tests/queries/0_stateless/02366_kql_test_sort.reference
  tests/queries/0_stateless/02366_kql_test_sort.sql
Labels: pr-bugfix

#249 `gettype()` function 2395
  src/Functions/Kusto/KqlGetType.cpp
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.cpp
  src/Parsers/Kusto/KustoFunctions/KQLGeneralFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLGeneralFunctions.h
  src/Parsers/tests/KQL/gtest_KQL_General.cpp
  tests/queries/0_stateless/02366_kql_func_general.reference
  tests/queries/0_stateless/02366_kql_func_general.sql
Labels: pr-feature

#250 bug fix 2174, 2175,1075(improvement)
  src/Parsers/Kusto/ParserKQLOperators.cpp
  tests/queries/0_stateless/02366_kql_operator_in_sql.reference
  tests/queries/0_stateless/02366_kql_operator_in_sql.sql
Labels: pr-bugfix

#236 Hash changes
  src/Functions/Kusto/kqlHash.cpp
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.cpp
  src/Parsers/Kusto/KustoFunctions/KQLHashFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLHashFunctions.h
  src/Parsers/tests/KQL/gtest_KQL_Hash.cpp
  tests/queries/0_stateless/02366_kql_func_hash.reference
  tests/queries/0_stateless/02366_kql_func_hash.sql
Labels: pr-feature

#261 Update release notes
  src/Parsers/Kusto/KQL_ReleaseNote.md
Labels: pr-not-for-changelog

#264 between native function
  src/Functions/Kusto/kqlBetween.cpp
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/ParserKQLOperators.cpp
  src/Parsers/TokenIterator.cpp
  src/Parsers/tests/KQL/gtest_KQL_operator.cpp
  tests/queries/0_stateless/02366_kql_operator_in_sql.sql
  tests/queries/0_stateless/02366_kql_operators.reference
  tests/queries/0_stateless/02366_kql_operators.sql
Labels: pr-feature

#269 Kusto p3 fix make series
  src/Parsers/Kusto/ParserKQLMakeSeries.cpp
  src/Parsers/Kusto/ParserKQLMakeSeries.h
  src/Parsers/Kusto/ParserKQLTopHitter.cpp
  src/Parsers/tests/KQL/gtest_KQL_MakeSeries.cpp
  tests/queries/0_stateless/02366_kql_makeseries.reference
  tests/queries/0_stateless/02366_kql_makeseries.sql
Labels: pr-improvement

#255 make_string function
  src/Functions/Kusto/kqlMakeString.cpp
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.cpp
  src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.h
  src/Parsers/tests/KQL/gtest_KQL_StringFunctions.cpp
  tests/queries/0_stateless/02366_kql_func_string.reference
  tests/queries/0_stateless/02366_kql_func_string.sql
Labels: pr-feature

#274 Implement indexof_regex
  src/Functions/Kusto/kqlIndexOfRegex.cpp
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.cpp
  src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
  src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.h
  src/Parsers/tests/KQL/gtest_KQL_StringFunctions.cpp
  tests/queries/0_stateless/02366_kql_func_general.sql
  tests/queries/0_stateless/02366_kql_func_string.reference
  tests/queries/0_stateless/02366_kql_func_string.sql
Labels: pr-feature

#276 support multiple output columns in arg_max and arg_min
  src/Parsers/Kusto/KQL_ReleaseNote.md
  src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
  src/Parsers/tests/KQL/gtest_KQL_AggregateFunctions.cpp
  tests/queries/0_stateless/02366_kql_summarize.reference
  tests/queries/0_stateless/02366_kql_summarize.sql
Labels: pr-bugfix
